task-tracker-pet-project/task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('', include('users.urls', namespace='users')),
]

task-tracker-pet-project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('edit-credentials/', views.edit_credentials, name='edit-credentials'),
]

task-tracker-pet-project/users/models.py
from django.db import models

# Create your models here.

task-tracker-pet-project/users/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Введите логин'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                self.add_error('username', '')
                self.add_error('password', '')
                raise forms.ValidationError('Неверный логин или пароль.')

        return super().clean()


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Введите логин'}))
    password1 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2')

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            self.add_error('password1', '')
        try:
            password_validation.validate_password(password1)
        except forms.ValidationError as error:
            self.add_error('password1', '')
        if password1.isdigit():
            self.add_error('password1', '')

        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            self.add_error('password1', '')
            raise forms.ValidationError('Пароли не совпадают.', code='password_mismatch')
        return password2


class ChangeLoginAndPasswordForm(forms.Form):
    username = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'placeholder': 'Новый логин'}))
    new_password1 = forms.CharField(label='', required=False,
                                    widget=forms.PasswordInput(attrs={'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(label='', required=False,
                                    widget=forms.PasswordInput(attrs={'placeholder': 'Повторите новый пароль'}))

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError('Пользователь с таким именем уже существует.')
        return username

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')
        if new_password2:
            try:
                password_validation.validate_password(new_password2)
            except forms.ValidationError as error:
                self.add_error('new_password1', ' ')
                self.cleaned_data['new_password1'] = new_password1
                raise forms.ValidationError(error)

        return new_password2

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')
        if new_password1 and new_password2:
            if new_password1 != new_password2:
                self.add_error('new_password1', ' ')
                self.add_error('new_password2', 'Пароли не совпадают.')

        if new_password1 and not new_password2:
            self.add_error('new_password2', 'Обязательное поле.')

        if not new_password1 and new_password2:
            self.add_error('new_password1', 'Обязательное поле.')

        return cleaned_data

task-tracker-pet-project/users/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from users.forms import LoginUserForm, RegisterUserForm, ChangeLoginAndPasswordForm


def register_user(request):
    if request.user.is_authenticated:
        return redirect('main_app:index')

    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('main_app:index')
    else:
        form = RegisterUserForm()

    return render(request, 'users/register.html', {'form': form})


def login_user(request):
    if request.user.is_authenticated:
        return redirect('main_app:index')

    if request.method == 'POST':
        form = LoginUserForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                return redirect('main_app:index')
    else:
        form = LoginUserForm()

    return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('users:login')


@require_POST
@login_required
def edit_credentials(request):
    form = ChangeLoginAndPasswordForm(request.POST)
    if form.is_valid():
        user = request.user
        username = form.cleaned_data['username']
        new_password = form.cleaned_data['new_password1']
        if username:
            user.username = username
        if new_password:
            user.set_password(new_password)
            # Сохраняем сессию после смены пароля
            update_session_auth_hash(request, user)
        user.save()
        logout(request)
        return JsonResponse({'success': True})
    else:
        errors = {field: form.errors[field][0] for field in form.errors}
        return JsonResponse({'success': False, 'errors': errors})

task-tracker-pet-project/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<main class="main">
    <div class="container">
        <div class="auth">
            <form method="post" class="auth__form">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <input type="{{ field.field.widget.input_type }}"
                           name="{{ field.name }}"
                           class="input auth__input {% if field.errors %}error{% endif %}"
                           placeholder="{{ field.field.widget.attrs.placeholder }}">
                    {{ field.errors }}
                    {% if forloop.last %}
                    {{ form.non_field_errors }}
                    {% endif %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-white">Войти</button>
                <a class="btn btn-white" href="{% url 'users:register' %}">Регистрация</a>
            </form>
        </div>
    </div>
</main>
<footer></footer>
{% endblock content %}

task-tracker-pet-project/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<main class="main">
    <div class="container">
        <div class="auth">
            <form method="post" class="auth__form">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <input type="{{ field.field.widget.input_type }}"
                           name="{{ field.name }}"
                           class="input auth__input {% if field.errors %}error{% endif %}"
                           placeholder="{{ field.field.widget.attrs.placeholder }}">
                    {{ field.errors }}
                    {% if forloop.last %}
                    {{ form.non_field_errors }}
                    {% endif %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-white">Зарегистрироваться</button>
                <a class="btn btn-white" href="{% url 'users:login' %}">Авторизация</a>
            </form>
        </div>
    </div>
</main>
<footer></footer>
{% endblock content %}