task-tracker-pet-project/main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('add-active-task/', views.add_active_task, name='add-active-task'),
    path('add-pending-task/', views.add_pending_task, name='add-pending-task'),
    path('finish-active-task/', views.finish_active_task, name='finish-active-task'),
    path('edit-active-task/<int:task_id>/', views.edit_active_task, name='edit-active-task'),
    path('make-active-task-pending/', views.make_active_task_pending, name='make-active-task-pending'),
    path('edit-pending-task/<int:task_id>/', views.edit_pending_task, name='edit-pending-task'),
    path('remove-pending-task/<int:task_id>/', views.remove_pending_task, name='remove-pending-task'),
    path('make-pending-task-active/', views.make_pending_task_active, name='make-pending-task-active'),
    path('add-completed-task/', views.add_completed_task, name='add-completed-task'),
    path('edit-completed-task/<int:task_id>/', views.edit_completed_task, name='edit-completed-task'),
    path('remove-completed-task/<int:task_id>/', views.remove_completed_task, name='remove-completed-task'),
    path('change-pending-tasks-order/', views.change_pending_tasks_order, name='change-pending-tasks-order'),
    path('load-next-completed-tasks/', views.load_next_completed_tasks, name='load-next-completed-tasks'),
]

task-tracker-pet-project/task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('', include('users.urls', namespace='users')),
]

task-tracker-pet-project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('edit-credentials/', views.edit_credentials, name='edit-credentials'),
]

task-tracker-pet-project/main_app/models.py
from datetime import timedelta, datetime
from typing import Optional

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class TaskList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    task_name = models.CharField(max_length=255)
    creation_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
    order = models.IntegerField(default=100000)
    active_task_start_time = models.DateTimeField(null=True, blank=True)
    completed_task_start_time = models.DateTimeField(null=True, blank=True)
    completed_task_end_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.task_name

    class Meta:
        verbose_name = 'Список задач'
        verbose_name_plural = 'Список задач'

    @staticmethod
    def timedelta_to_minutes_and_seconds(td: timedelta) -> str:
        """
        Возвращает строку формата MM:SS
        """
        minutes = td.seconds // 60
        seconds = td.seconds % 60
        return '{:02}:{:02}'.format(minutes, seconds)

    def get_active_task_start_time(self) -> str:
        """
        Возвращает время начала активной задачи в формате HH:MM
        """
        local_time = timezone.localtime(self.active_task_start_time, timezone=timezone.get_current_timezone())
        return local_time.strftime('%H:%M')

    @staticmethod
    def get_active_task_current_time() -> str:
        """
        Возвращает текущее время активной задачи в формате HH:MM
        """
        return datetime.now().strftime('%H:%M')

    def get_active_task_time_difference(self) -> str:
        """
        Возвращает разницу во времени между текущим временем и временем начала активной задачи
        """
        time_difference = timezone.now() - self.active_task_start_time
        return self.timedelta_to_minutes_and_seconds(time_difference)

    def get_completed_task_start_time(self) -> Optional[str]:
        """
        Возвращает время начала завершенной задачи в формате HH:MM, если оно определено
        """
        if self.completed_task_start_time:
            local_time = timezone.localtime(self.completed_task_start_time, timezone=timezone.get_current_timezone())
            return local_time.strftime('%H:%M')
        return None

    def get_completed_task_end_time(self) -> Optional[str]:
        """
        Возвращает время окончания завершенной задачи в формате HH:MM, если оно определено
        """
        if self.completed_task_end_time:
            local_time = timezone.localtime(self.completed_task_end_time, timezone=timezone.get_current_timezone())
            return local_time.strftime('%H:%M')
        return None

    def get_completed_task_time_difference(self) -> Optional[str]:
        """
        Возвращает разницу во времени между окончанием и началом завершенной задачи в часах и минутах
        """
        if self.completed_task_start_time and self.completed_task_end_time:
            total_seconds = (self.completed_task_end_time - self.completed_task_start_time).total_seconds()
            hours = total_seconds // 3600
            minutes = (total_seconds % 3600) // 60
            return f'{int(hours)} ч {int(minutes)} м' if hours > 0 else f'{int(minutes)} м'
        return None

task-tracker-pet-project/main_app/forms.py
from django import forms


class TaskForm(forms.Form):
    task_name = forms.CharField(max_length=255)


class CompletedTaskForm(forms.Form):
    task_name = forms.CharField(max_length=255)
    task_start = forms.CharField(required=False)
    task_end = forms.CharField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        task_start = cleaned_data.get('task_start')
        task_end = cleaned_data.get('task_end')
        # Проверяем, что если было предоставлено task_start или task_end, то должны быть предоставлены оба поля
        if (task_start and not task_end) or (not task_start and task_end):
            raise forms.ValidationError('Provide both task start and end time')

        # Проверяем, что время окончания задачи превышает время начала
        if task_start > task_end:
            raise forms.ValidationError('End time must be greater than start time')

        return cleaned_data

task-tracker-pet-project/main_app/views.py
import json
from datetime import datetime

from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.decorators.http import require_GET, require_POST

from users.forms import ChangeLoginAndPasswordForm
from .forms import TaskForm, CompletedTaskForm
from .models import TaskList
from .utils import get_completed_tasks_total_time, get_time_difference, get_today_date_with_specified_time, \
    parse_date, date_to_day_month_weekday, MONTHS


@require_GET
@login_required
def index(request):
    # Получаем активную задачу на таймере
    active_task = TaskList.objects.filter(user=request.user, is_active=True).first()

    # Получаем активные задачи не на таймере
    pending_tasks = TaskList.objects.filter(user=request.user, is_active=False, is_completed=False).order_by('order')

    # Получаем выполненные задачи с временными интервалами
    completed_tasks_with_time = TaskList.objects.filter(
        user=request.user,
        is_completed=True,
        completed_task_start_time__date=timezone.now().date()
    ).order_by('-completed_task_start_time')

    # Вычисляем суммарное время выполненных задач с временными интервалами
    completed_tasks_total_time = get_completed_tasks_total_time(completed_tasks_with_time)

    # Получаем выполненные задачи без временных интервалов
    completed_tasks_without_time = TaskList.objects.filter(
        user=request.user,
        is_completed=True,
        creation_time__date=timezone.now().date(),
        completed_task_start_time__isnull=True
    )

    # Форма смены логина и пароля
    form = ChangeLoginAndPasswordForm(request.POST)

    return render(request, 'main_app/index.html', {
        'active_task': active_task,
        'pending_tasks': pending_tasks,
        'completed_tasks_with_time': completed_tasks_with_time,
        'completed_tasks_total_time': completed_tasks_total_time,
        'completed_tasks_without_time': completed_tasks_without_time,
        'month_day': timezone.now().date().day,
        'month': MONTHS.get(timezone.now().date().month),
        'form': form,
    })


@require_POST
@login_required
def add_active_task(request):
    form = TaskForm(request.POST)
    # Ищем в БД активную задачу
    active_task = TaskList.objects.filter(user=request.user, is_active=True).first()
    # Продолжаем работу если в БД не нашлась активная задача
    if not active_task:
        if form.is_valid():
            task = TaskList.objects.create(user=request.user, task_name=form.cleaned_data.get('task_name'))
            task.is_active = True
            task.active_task_start_time = timezone.now()
            task.save()
            start = datetime.now().strftime('%H:%M')
            return JsonResponse({'success': True, 'task_id': task.id, 'start': start})
        else:
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        return JsonResponse({'success': False, 'message': 'There is already an active task'})


@require_POST
@login_required
def add_pending_task(request):
    form = TaskForm(request.POST)
    if form.is_valid():
        task = TaskList.objects.create(user=request.user, task_name=form.cleaned_data.get('task_name'))
        task.is_active = False
        task.save()
        return JsonResponse({'success': True, 'task_id': task.pk})
    else:
        return JsonResponse({'success': False, 'errors': form.errors}, status=400)


@require_POST
@login_required
def finish_active_task(request):
    body_unicode = request.body.decode('utf-8')
    pk = json.loads(body_unicode).get('taskId')
    if pk:
        try:
            task = TaskList.objects.get(pk=pk)
            if not task.is_active:
                return JsonResponse({'success': False, 'message': 'Provide id of an active task'}, status=400)
            task.is_active = False
            task.is_completed = True
            task.completed_task_start_time = task.active_task_start_time
            task.completed_task_end_time = timezone.now()
            task.save()
            return JsonResponse({
                'success': True,
                'task_duration': get_time_difference(task.completed_task_start_time, task.completed_task_end_time),
            })
        except TaskList.DoesNotExist:
            return JsonResponse({'success': False, 'message': f'Task with id {pk} does not exist'}, status=400)
    else:
        return JsonResponse({'success': False, 'message': 'Provide task pk'}, status=400)


@require_POST
@login_required
def edit_active_task(request, task_id):
    form = TaskForm(request.POST)
    if form.is_valid():
        try:
            task = TaskList.objects.get(pk=task_id)
            if not task.is_active:
                return JsonResponse({'success': False, 'message': 'Provide id of an active task'}, status=400)
            task.task_name = form.cleaned_data.get('task_name')
            task.save()
            return JsonResponse({'success': True, 'task_id': task_id})
        except TaskList.DoesNotExist:
            return JsonResponse({'success': False, 'message': f'Task with id {task_id} does not exist'}, status=400)
    else:
        return JsonResponse({'success': False, 'errors': form.errors}, status=400)


@require_POST
@login_required
def make_active_task_pending(request):
    pk = request.POST.get('task_id')
    if pk:
        try:
            task = TaskList.objects.get(pk=pk)
            if not task.is_active:
                return JsonResponse({'success': False, 'message': 'Provide id of an active task'}, status=400)
            task.is_active = False
            task.active_task_start_time = None
            task.order = 0
            task.save()
            # Получаем активные задачи не на таймере
            tasks = TaskList.objects.filter(user=request.user, is_active=False, is_completed=False).order_by('order')
            # Устанавливаем порядковый номер для каждой задачи
            for num, task in enumerate(tasks, start=1):
                task.order = num
                task.save()

            return JsonResponse({'success': True})
        except TaskList.DoesNotExist:
            return JsonResponse({'success': False, 'message': f'Task with id {pk} does not exist'}, status=400)
    else:
        return JsonResponse({'success': False, 'message': 'Provide task pk'}, status=400)


@require_POST
@login_required
def edit_pending_task(request, task_id):
    form = TaskForm(request.POST)
    if form.is_valid():
        try:
            task = TaskList.objects.get(pk=task_id)
            if task.is_active:
                return JsonResponse({'success': False, 'message': 'Provide id of a pending task'}, status=400)
            task.task_name = form.cleaned_data.get('task_name')
            task.save()
            return JsonResponse({'success': True, 'task_id': task_id})
        except TaskList.DoesNotExist:
            return JsonResponse({'success': False, 'message': f'Task with id {task_id} does not exist'}, status=400)
    else:
        return JsonResponse({'success': False, 'errors': form.errors}, status=400)


@require_POST
@login_required
def remove_pending_task(request, task_id):
    try:
        task = TaskList.objects.get(pk=task_id)
        if task.is_active:
            return JsonResponse({'success': False, 'message': 'Provide id of a pending task'}, status=400)
        task.delete()
        return JsonResponse({'success': True, 'task_id': task_id})
    except TaskList.DoesNotExist:
        return JsonResponse({'success': False, 'message': f'Task with id {task_id} does not exist'}, status=400)


@require_POST
@login_required
def make_pending_task_active(request):
    body_unicode = request.body.decode('utf-8')
    pk = json.loads(body_unicode).get('taskId')
    if pk:
        try:
            task = TaskList.objects.get(pk=pk)
            if task.is_active:
                return JsonResponse({'success': False, 'message': 'Provide id of a pending task'}, status=400)
            task.is_active = True
            task.active_task_start_time = timezone.now()
            task_name = task.task_name
            task.save()
            return JsonResponse({
                'success': True,
                'task_name': task_name,
                'task_id': pk,
                'start': datetime.now().strftime('%H:%M'),
            })
        except TaskList.DoesNotExist:
            return JsonResponse({'success': False, 'message': f'Task with id {pk} does not exist'}, status=400)
    else:
        return JsonResponse({'success': False, 'message': 'Provide task pk'}, status=400)


@require_POST
@login_required
def add_completed_task(request):
    form = CompletedTaskForm(request.POST)
    if form.is_valid():
        task_name = form.cleaned_data.get('task_name')
        task_start_time = form.cleaned_data.get('task_start')
        task_end_time = form.cleaned_data.get('task_end')
        try:
            new_task = TaskList.objects.create(
                user=request.user,
                task_name=task_name,
                is_completed=True,
                completed_task_start_time=get_today_date_with_specified_time(task_start_time),
                completed_task_end_time=get_today_date_with_specified_time(task_end_time),
            )

            # Если у задачи определены время начала и окончания
            if task_start_time and task_end_time:
                task_duration = get_time_difference(new_task.completed_task_start_time,
                                                    new_task.completed_task_end_time)
            else:
                task_duration = None

            return JsonResponse({
                'success': True,
                'task_id': new_task.pk,
                'task_start_time': new_task.completed_task_start_time,
                'task_end_time': new_task.completed_task_end_time,
                'task_duration': task_duration,
            })

task-tracker-pet-project/main_app/templates/main_app/index.html
{% extends 'base.html' %}

{% block content %}
<main class="main">
    <div class="container">
        <div class="tasks">
            <div class="tasks__form">
                <form method="POST" id="tasks__form">
                    {% csrf_token %}
                    <input type="text" class="input" name="task_name">
                    <i class="_icon-plus plus-icon" onclick="addPendingTask()"></i>
                    <i class="_icon-play finish-active-task-warning-popup"
                       href="#finish-active-task-warning-popup"
                       onclick="addActiveTask()"></i>
                </form>
            </div>
            <div class="tasks__block active__tasks">
                <ul class="tasks__block__list sortable__list" id="upper__tasks__block__list">
                    {% if active_task %}
                    <li class="tasks__block__list__item list__item active__task">
                        <a href="#edit-active-task-popup"
                           class="list__item__link popup-link"
                           data-item-id="{{ active_task.pk }}">
                            <div class="list__item__title">
                                {{ active_task }}
                            </div>
                            <div class="list__item__strend">
                                {{ active_task.get_active_task_start_time }} -
                                {{ active_task.get_active_task_current_time }}
                            </div>
                            <div class="list__item__spendtime">
                                <p>{{ active_task.get_active_task_time_difference }}</p>
                                <i class="_icon-stop-circle" onclick="finishActiveTask(event)"></i>
                            </div>
                        </a>
                    </li>
                    {% endif %}
                    {% for task in pending_tasks %}
                    <li class="tasks__block__list__item list__item waiting__task">
                        <a href="#edit-task-popup" class="list__item__link popup-link" data-item-id="{{ task.pk }}">
                            <div class="list__item__title">{{ task }}</div>
                            <div class="list__item__run">
                                <i class="_icon-play"></i>
                            </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tasks__block">
                <div class="tasks__block__info">
                    <div class="tasks__block__info__title">
                        <h2>Сегодня</h2>
                        <a href="#add-completed-task-popup" class="popup-link">
                            <i class="_icon-plus"></i>
                        </a>
                    </div>
                    <div class="tasks__block__info__time">
                        {% if completed_tasks_total_time != "0 м" %}
                        {{ completed_tasks_total_time }}
                        {% endif %}
                    </div>
                </div>
                <ul class="tasks__block__list" id="today__tasks__block__list">
                    {% for task in completed_tasks_with_time %}
                    <li class="tasks__block__list__item list__item done with__time">
                        <a href="#edit-completed-task-popup" class="list__item__link popup-link"
                           data-item-id="{{ task.pk }}">
                            <div class="list__item__title">{{ task }}</div>
                            <div class="list__item__strend">
                                {{ task.get_completed_task_start_time }} -
                                {{ task.get_completed_task_end_time }}
                            </div>
                            <div class="list__item__spendtime">
                                {{ task.get_completed_task_time_difference }}
                            </div>
                        </a>
                    </li>
                    {% endfor %}
                    {% for task in completed_tasks_without_time %}
                    <li class="tasks__block__list__item list__item done">
                        <a href="#edit-completed-task-popup" class="list__item__link popup-link"
                           data-item-id="{{ task.pk }}">
                            <div class="list__item__title">{{ task }}</div>
                            <div class="list__item__strend"></div>
                            <div class="list__item__spendtime"></div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

{% block footer %}
<footer class="footer">
    <div class="container">
        <ul class="footer__options">
            <li class="footer__options__item download-more">
                <a href="">
                    <i class="_icon-download"></i>
                    <p>Загрузить ещё</p>
                </a>
            </li>
            <li class="footer__options__item today-only display-none">
                <a href="">
                    <i class="_icon-calendar"></i>
                    <p>Только сегодня</p>
                </a>
            </li>
            <li class="footer__options__item">
                <a href="#profile-edit-popup" class="popup-link">
                    <i class="_icon-user"></i>
                    {% if user.is_authenticated %}
                    <p>{{ user.username }}</p>
                    {% else %}
                    <i class="_icon-user"></i>
                    <p><a href="{% url 'users:login' %}">Войти</a></p>
                    {% endif %}
                </a>
            </li>
        </ul>
    </div>
</footer>
{% endblock footer %}

{% block popups %}
{% include 'main_app/popups.html' %}
{% endblock popups %}

task-tracker-pet-project/main_app/templates/main_app/popups.html
<div class="popup" id="edit-active-task-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Редактирование активной задачи</h3>
            </div>
            <form method="POST" class="popup__form" id="edit__active__popup__form">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="">
                <div class="popup__content-item popup__form-input">
                    <input type="text" class="input task__name" name="task_name">
                </div>
                <div class="popup__content-item popup__form-btns">
                    <button type="button" class="btn btn-white" onclick="editActiveTask()">
                        <i class="_icon-save"></i>Сохранить
                    </button>
                    <button type="button" class="btn btn-black" onclick="makeActiveTaskPending()">
                        <i class="_icon-trash"></i>Отменить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="popup" id="less-than-minute-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Задачи длительностью менее 1 минуты не сохраняются</h3>
            </div>
        </div>
    </div>
</div>

<div class="popup" id="finish-active-task-warning-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Сначала завершите текущую задачу</h3>
            </div>
        </div>
    </div>
</div>

<div class="popup" id="edit-task-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Редактирование задачи</h3>
            </div>
            <form method="POST" class="popup__form" id="edit__pending__popup__form">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="">
                <div class="popup__content-item popup__form-input">
                    <input type="text" class="input task__name" name="task_name">
                </div>
                <div class="popup__content-item popup__form-btns">
                    <button type="button" class="btn btn-white" onclick="editPendingTask()">
                        <i class="_icon-save"></i>Сохранить
                    </button>
                    <button type="button" class="btn btn-black" onclick="removePendingTask()">
                        <i class="_icon-trash"></i>Удалить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="popup" id="add-completed-task-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Добавление выполненной задачи</h3>
            </div>
            <form method="post" class="popup__form" id="add__completed__task__popup__form">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="">
                <div class="popup__content-item popup__form-input">
                    <input type="text" class="input task__name" name="task_name">
                </div>
                <div class="popup__content-item popup__form-range">
                    <div class="popup__form-range__inputs">
                        <input type="text" class="input task__start" name="task_start">
                        <span>-</span>
                        <input type="text" class="input task__end" name="task_end">
                    </div>
                    <div class="popup__form-range__time"></div>
                </div>
                <div class="popup__content-item popup__form-day">
                    <i class="_icon-calendar-date"></i>
                    <p>{{ month_day }} {{ month }}</p>
                </div>
                <div class="popup__content-item popup__form-btns">
                    <button type="button" class="btn btn-white" onclick="addCompletedTask()">
                        <i class="_icon-save"></i>Сохранить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="popup" id="edit-completed-task-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Редактирование выполненной задачи</h3>
            </div>
            <form method="post" class="popup__form" id="edit__completed__task__popup__form">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="">
                <div class="popup__content-item popup__form-input">
                    <input type="text" class="input task__name" name="task_name">
                </div>
                <div class="popup__content-item popup__form-range">
                    <div class="popup__form-range__inputs">
                        <input type="text" class="input task__start" name="task_start">
                        <span>-</span>
                        <input type="text" class="input task__end" name="task_end">
                    </div>
                    <div class="popup__form-range__time"></div>
                </div>
                <div class="popup__content-item popup__form-day">
                    <i class="_icon-calendar-date"></i>
                    <p>{{ month_day }} {{ month }}</p>
                </div>
                <div class="popup__content-item popup__form-btns">
                    <button type="button" class="btn btn-white" onclick="editCompletedTask()">
                        <i class="_icon-save"></i>Сохранить
                    </button>
                    <button type="button" class="btn btn-black" onclick="removeCompletedTask()">
                        <i class="_icon-trash"></i>Удалить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="popup" id="profile-edit-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Редактирование профиля</h3>
            </div>
            <form method="post" class="popup__form" id="edit__credentials__popup__form">
                {% csrf_token %}
                {% for field in form %}
                <div class="popup__content-item popup__form-input">
                    <input type="{{ field.field.widget.input_type }}"
                           name="{{ field.name }}"
                           class="input auth__input {% if field.errors %}error{% endif %}"
                           placeholder="{{ field.field.widget.attrs.placeholder }}">
                </div>
                {% if field.errors %}
                <ul class="profile__edit__errors">
                    {% for error in field.errors %}
                    <div id="{{ field.name }}__error">
                        {{ error }}
                    </div>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endfor %}
                <div class="popup__content-item popup__form-btns">
                    <button type="button" class="btn btn-white" onclick="editCredentials()">
                        <i class="_icon-save"></i>Сохранить
                    </button>
                    <a href="{% url 'users:logout' %}" class="btn btn-black">
                        <i class="_icon-log-out"></i>Выйти
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="popup" id="end-of-tasks-warning-popup">
    <div class="popup__body">
        <div class="popup__content">
            <a href="#" class="popup__close close-popup"><i class="_icon-close"></i></a>
            <div class="popup__title">
                <h3>Нет задач за меньшую дату</h3>
            </div>
        </div>
    </div>
</div>